name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master
  - main
  - release/*

# Parameters that can be specified when running the pipeline
parameters:
  - name: build
    type: boolean
    default: true
  - name: trivy
    type: boolean
    default: false
    displayName: Scan Container with Trivy
  - name: blackduck
    type: boolean
    default: false
    displayName: Scan Code with BlackDuck
  - name: acr_cleanup
    type: boolean
    default: true
    displayName: Purge Images in Container Registry
  - name: debug_mode
    type: boolean
    default: false
    displayName: Build in Debug Mode with Assertions


variables:
  - name: app.key
    value: way
  - name: app.name
    value: valhalla
  - name: run.build
    value: ${{ parameters.build }}
  - name: blackduck.enabled
    value: ${{ parameters.blackduck }}
  - name: trivy.enabled
    value: ${{ parameters.trivy }}
  - name: run.acr.cleanup
    value: ${{ parameters.acr_cleanup }}
  - name: build.debug.mode
    value: ${{ parameters.debug_mode }}

stages:
  # BUILD
  - template: pipeline/build/stage.yml
    parameters:
      name: build
      variables:
        - way.emea.share
        - blackduck
